name: Build Ansible Collection

on:
    push:
        branches: ["main", "stable", "release/v*", "build_collection"]
    pull_request:
        branches: ["main", "stable", "release/v*", "build_collection"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python environment
          run: |
            sudo apt-get install python3-pip
            pip install ansible
        - name: Build collection archive
          run: ansible-galaxy collection build rekey_variables
        - name: Upload archive (optional)
          uses: actions/upload-artifact@v3
          with:
            name: collection_archive
            path: ./rekey_variables.tar.gz
